export const videoBase = "https://www.youtube.com/embed/";

export const courseDefault = {
  videoBase: videoBase,
  statsText: [
    { top: "Number of Classes" },
    { top: "Duration", bottom: "Min Per Class" },
    { top: "Live-class ratio" },
    { top: "Age", bottom: "Years" },
    { top: "Cost", end: "$", bottom: "per Class" },
  ],
};
export const courseNotSelfPaced = {
  videoBase: videoBase,
  statsText: [
    { top: "Number of Classes" },
    { top: "Duration", bottom: "Hours" },
    { top: "Live-class ratio" },
    { top: "Age", bottom: "Years" },
    { top: "Cost", end: "$", bottom: "per Course" },
  ],
};

/* 
Optional Fields
instructor_id, extraShow, statsText.top, statsText.bottom, statsText.end, statsText.start
*/

export const courseList:any = [
  /* Financial Literacy  */
  //8-10
  {
    id: 101,
    instructor_id: 1,
    title: "Financial Literacy - Foundations",
    slug: "financial-literacy-foundations",
    age: "8-10",
    home:false,
    credits: true,
    self_paced: false,
    desc: "Become financially savvy in managing money matters in a fun & interactive manner, helping develop the right behaviour & attitude towards money.",
    duration: "6 Classes, Once per Week",
    cost: "10",
    objective:"Introducing pre-teens the concept of money and various institutions handling money in modern society.",
    stats: ["6", "60", "1:6", "8-10", "10"],
    timeline: {
      "Money Basics": "Origin of money and how money is essential for modern society",
      "Banking": "Introduction to banks",
      "Saving and  Investments": "How can we save money for future",
      "Insurance": "What is insurance",
      "Price and Inflation": "Why price of items fluctuates",
      "Smart  Money Habits": "Why save money and how you can do ?",
    },
    image: "/images/courses/fl.png",
    video: "m2A7H9OFahI",
    ...courseDefault,
  },
  //11-12
  {
    id: 102,
    instructor_id: 1,
    title: "Financial Literacy - Money Smart",
    slug: "financial-literacy-money-smart",
    home:true,
    age: "11-12",
    credits: true,
    self_paced: false,
    desc: "Become financially savvy in managing money matters in a fun & interactive manner, helping develop the right behaviour & attitude towards money.",
    duration: "6 Classes, Once per Week",
    cost: "10",
    objective:"Rising teens get the concept of money, banking, insurance and important of being responsible consumers.",
    stats: ["6", "60", "1:6", "11-12", "10"],
    timeline: {
      "Money Basics": "Evolution of money , concepts of  income, expense and saving",
      "Banking": "Introdction to banks, types of accounts and banking tips",
      "Saving and  Investments": "Concept of saving, investments and how to set saving goals",
      "Insurance": "Introduction to insurance and type of insurances",
      "Price and Inflation": "Inflation basics and effect of inflation in society",
      "Smart  Money Habits": "Saving for future and emergency funds. Types and problems of debts",
    },
    image: "/images/courses/fl.png",
    video: "m2A7H9OFahI",
    ...courseDefault,
  },
  //13-14
  {
    id: 103,
    instructor_id: 1,
    title: "Financial Literacy - New Age",
    slug: "financial-literacy-new-age",
    home:false,
    age: "13-14",
    credits: true,
    self_paced: false,
    desc: "Become financially savvy in managing money matters in a fun & interactive manner, helping develop the right behaviour & attitude towards money.",
    duration: "6 Classes, Once per Week",
    cost: "15",
    objective:"Introducing teens to various aspects of finance, banking, insurance, inflation, investments and responsible money management.",
    stats: ["6", "60", "1:6", "13-14", "15"],
    timeline: {
      "Money Basics": "Basics of currency,kinds of transactions  and monetory flow",
      "Banking": "Banking basics, Digital payments and types of banking accounts",
      "Saving and Investments": "Introduction to  aspects of investments, risk vs rewards as well as concepts growth and liquicty",
      "Insurance": "Introduction to Insurance basics, types of insurances and claims",
      "Price and Inflation": "Inflation and deflation - causes and making money",
      "Smart  Money Habits": "Avoiding debt,balancing budget, benefits of compounding and how to start investments.",
    },
    image: "/images/courses/fl.png",
    video: "m2A7H9OFahI",
    ...courseDefault,
  },
  //8-10  SP
  {
    id: 123,
    instructor_id: 1,
    title: "Financial Literacy - Foundations (Self-Paced)",
    slug: "financial-literacy-foundations-self-paced",
    home:false,
    age: "8-10",
    credits: false,
    self_paced: true,
    desc: "Become financially savvy in managing money matters in a fun & interactive manner, helping develop the right behaviour & attitude towards money.",
    duration: "4 Hours Self-Paced Simulation Based Learning",
    cost: "15",
    objective:"Self paced learning for young children  on various aspects of finance, banking, insurance , inflation, investments and responsible money management",
    stats: ["Self Paced", "4", "-", "8-10", "15"],
    timeline: {
      "Money Basics": "Origin of money and how money is essential for modern society",
      "Banking": "Introduction to banks",
      "Saving and  Investments": "How can we save money for future",
      "Insurance": "What is insurance",
      "Price and Inflation": "Why price of items fluctuates",
      "Smart  Money Habits": "Why save money and how you can do?",
    },
    image: "/images/courses/fl.png",
    video: "m2A7H9OFahI",
    ...courseNotSelfPaced,
  },
  //11-12 SP
  {
    id: 124,
    instructor_id: 1,
    title: "Financial Literacy - Money Smart (Self-Paced)",
    slug: "financial-literacy-money-smart-self-paced",
    home:false,
    age: "11-12",
    credits: false,
    self_paced: true,
    desc: "Become financially savvy in managing money matters in a fun & interactive manner, helping develop the right behaviour & attitude towards money.",
    duration: "6 Hours Self-Paced Simulation Based Learning",
    cost: "10",
    objective:"Rising teens get the concept of money, banking, insurance and important of being responsible consumers.",
    stats: ["Self Paced", "6", "-", "11-12", "15"],
    timeline: {
      "Money Basics": "Evolution of money , concepts of  income, expense and saving",
      "Banking": "Introdction to banks, types of accounts and banking tips",
      "Saving and  Investments": "Concept of saving, investments and how to set saving goals",
      "Insurance": "Introduction to insurance and type of insurances",
      "Price and Inflation": "Inflation basics and effect of inflation in society",
      "Smart  Money Habits": "Saving for future and emergency funds. Types and problems of debts",
    },
    image: "/images/courses/fl.png",
    video: "m2A7H9OFahI",
    ...courseNotSelfPaced,
  },
  //13-14 SP
  {
    id: 125,
    instructor_id: 1,
    title: "Financial Literacy - New Age (Self-Paced)",
    slug: "financial-literacy-new-age-self-paced",
    home:false,
    age: "13-14",
    credits: false,
    self_paced: true,
    desc: "Become financially savvy in managing money matters in a fun & interactive manner, helping develop the right behaviour & attitude towards money.",
    duration: "6 Hours Self-Paced Simulation Based Learning",
    cost: "15",
    objective:"Introducing teens to various aspects of finance, banking, insurance, inflation, investments and responsible money management.",
    stats: ["Self Paced", "6", "-", "13-14", "15"],
    timeline: {
      "Money Basics": "Basics of currency,kinds of transactions  and monetory flow",
      "Banking": "Banking basics, Digital payments and types of banking accounts",
      "Saving and Investments": "Introduction to  aspects of investments, risk vs rewards as well as concepts growth and liquicty",
      "Insurance": "Introduction to Insurance basics, types of insurances and claims",
      "Price and Inflation": "Inflation and deflation - causes and making money",
      "Smart  Money Habits": "Avoiding debt,balancing budget, benefits of compounding and how to start investments.",
    },
    image: "/images/courses/fl.png",
    video: "m2A7H9OFahI",
    ...courseNotSelfPaced,
  },
  /* Digital Literacy */
  // 8-10
  {
    id: 104,
    instructor_id: 1,
    title: "Digital Literacy",
    slug: "digital-literacy-8-10",
      age: "8-10",
    home:false,
    credits: true,
    self_paced: false,
    desc: "Develop knowledge, skills and attitudes to be both safe and empowered in an increasingly digital world.",
    duration: "5 Classes, Once per Week",
    cost: "10",
    objective:"Ensuring young children safely navigate, communicate and evaluate information coming from various digital channels like internet, mobile and social media.",
    stats: ["5", "60", "1:6", "8-10", "10"],
    timeline: {
      "Digital Footprint": `Introducing children to the need of using internet safely understand "stranger danger" in the internet`,
      "Media Literacy": `Introducing children real and what is fake  news and advertisment in the digital world`,
      "Online Communication": `Concepts of how to text or join a group while protecting your and parents information and reputation`,
      "How to spot a bully": `Identify and prevent cyber bullying`,
      "Media balance": `How much time is a good amount of time with media and internet`,
    },
    image: "/images/courses/dl.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  },
  // 11-12
  {
    id: 105,
    instructor_id: 1,
    title: "Digital Literacy",
    slug: "digital-literacy-11-12",
    age: "11-12",
    home:true,
    credits: true,
    self_paced: false,
    desc: "Develop knowledge, skills and attitudes to be both safe and empowered in an increasingly digital world.",
    duration: "6 Classes, Once per Week",
    cost: "10",
    objective:"Teaching pre-teens find, evaluate, and clearly communicate information through typing and other media on various digital platforms in a safe manner.",
    stats: ["6", "60", "1:6", "11-12", "10"],
    timeline: {
      "Digital Footprint": `Introducing children how your digital interactions create your virtual profiles`,
      "Media Literacy": `How to spot fake news and personas and improtance of sharing information prudently`,
      "Online Communication": `Introduction to electronic communication etiquette and social media do's and don'ts.`,
      "How to spot a bully": `Introduction to digital drama and cyber bullying in a connected world and how to prevent being bullied`,
      "Media balance": `Taking action and making wise media choices based on your other activities`,
      "Digital wellbeing": `Developing a media plan`,
    },
    image: "/images/courses/dl.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  },
  // 11-12 SP
  {
    id: 126,
    instructor_id: 1,
    title: "Digital Literacy (Self-Paced)",
    slug: "digital-literacy-11-12-self-paced",
    age: "11-12",
    home:false,
    credits: false,
    self_paced: true,
    desc: "Develop knowledge, skills and attitudes to be both safe and empowered in an increasingly digital world.",
    duration: "4 Hours Self-Paced Simulation Based Learning",
    cost: "20",
    objective:"Teaching pre-teens find, evaluate, and clearly communicate information through typing and other media on various digital platforms in a safe manner.",
    stats: ["Self Paced", "4", "-", "11-12", "20"],
    timeline: {
      "Digital Footprint": `Introducing children how your digital interactions create your virtual profiles`,
      "Media Literacy": `How to spot fake news and personas and improtance of sharing information prudently`,
      "Online Communication": `Introduction to electronic communication etiquette and social media do's and don'ts.`,
      "How to spot a bully": `Introduction to digital drama and cyber bullying in a connected world and how to prevent being bullied`,
      "Media balance": `Taking action and making wise media choices based on your other activities`,
      "Digital wellbeing": `Developing a media plan`,
    },
    image: "/images/courses/dl.png",
    video: "CGmDCm-bD9k",
    ...courseNotSelfPaced,
  },
  // 13-14
  {
    id: 106,
    instructor_id: 1,
    title: "Digital Literacy",
    slug: "digital-literacy-13-14",
    age: "13-14",
    home:false,
    credits: true,
    self_paced: false,
    desc: "Develop knowledge, skills and attitudes to be both safe and empowered in an increasingly digital world.",
    duration: "6 Classes, Once per Week",
    cost: "10",
    objective:"Introducing teens on aspects of safe and acceptable way of information sharing, creation and consuption in digital platforms and devices in the internet and  social media space",
    stats: ["6", "60", "1:6", "13-14", "10"],
    timeline: {
      "Digital Citizenship": `Introducing teens about the importance of digital footprint, PII data, identity theft and importance of online reputation`,
      "Media Literacy": `Introducing teens to the fake news, its impact in society and how to shield themselves from bias`,
      "Digital etiquette": `Introducing safe communication practices and digital communication etiquette`,
      "Digital Drama": `Various kind of digital dramas, including cyber bullying and its impacts and consequences`,
      "Taking actions": `How to spot, take action against cyber bullying and hate speech in social media`,
      "Media Balance & wellbeing": `Learning media choices and how the media choices your education and brain. Helping to develop a media plan for your success`,
    },
    image: "/images/courses/dl.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  },
  // 13-14 SP
  {
    id: 127,
    instructor_id: 1,
    title: "Digital Literacy (Self - Paced)",
    slug: "digital-literacy-13-14-self-paced",
    age: "13-14",
    home:false,
    credits: false,
    self_paced: true,
    desc: "Develop knowledge, skills and attitudes to be both safe and empowered in an increasingly digital world.",
    duration: "6 Hours Self-Paced Simulation Based Learning",
    cost: "20",
    objective:"Introducing teens on aspects of safe and acceptable way of information sharing, creation and consuption in digital platforms and devices in the internet and  social media space",
    stats: ["6", "60", "1:6", "13-14", "20"],
    timeline: {
      "Digital Citizenship": `Introducing teens about the importance of digital footprint, PII data, identity theft and importance of online reputation`,
      "Media Literacy": `Introducing teens to the fake news, its impact in society and how to shield themselves from bias`,
      "Digital etiquette": `Introducing safe communication practices and digital communication etiquette`,
      "Digital Drama": `Various kind of digital dramas, including cyber bullying and its impacts and consequences`,
      "Taking actions": `How to spot, take action against cyber bullying and hate speech in social media`,
      "Media Balance & wellbeing": `Learning media choices and how the media choices your education and brain. Helping to develop a media plan for your success`,
    },
    image: "/images/courses/dl.png",
    video: "CGmDCm-bD9k",
    ...courseNotSelfPaced,
  },
  /* Cyber Security */
  // 11-12
  {
    id: 108,
    instructor_id: 1,
    title: "Cyber Security",
    slug: "cyber-security-11-12",
    age: "11-12",
    home:true,
    credits: true,
    self_paced: false,
    desc: "Introducing children to navigate the cyberworld in a safe and secure way.",
    duration: "5 Classes, Once per Week",
    cost: "15",
    objective:"Introducing pre-teens to cyber security risks and educating  them on concepts of how can safely be in this networked world.",
    stats: ["5", "60", "1:6", "11-12", "15"],
    timeline: {
      "Cyber Security - Introduction": `Introducing pre-teens to importance of cyber security and various scams in digital world`,
      "Online Privacy": `What is privacy and why it is important. How can you help to protect yours and your family's information`,
      "Mobile Seurity": `How to use apps in mobile device safely`,
      "Social Media": `How to use social media safely`,
      "Cyber Security - Best practices": `Protecting your devices , profiles and emails from cyber criminals`,
    },
    image: "/images/courses/isl.png",
    video: "vnUBqfiLZIk",
    ...courseDefault,
  },
  // 13-14
  {
    id: 109,
    instructor_id: 1,
    title: "Cyber Security",
    slug: "cyber-security-13-14",
    age: "13-14",
    home:false,
    credits: true,
    self_paced: false,
    desc: "Enabling teens to access devices and use social media in a secure way while creating a positive digital profile.",
    duration: "6 Classes, Once per Week",
    cost: "15",
    objective:"Letting teens know the needs of cyber security, data privacy and identity  management in internet and social media. Given them high level steps to secure their online presence.",
    stats: ["6", "60", "1:6", "13-14", "15"],
    timeline: {
      "Cyber Security - Introduction": `Introduce students to various terms and types of cyber security issues in the modern digital world.`,
      "Privacy and Identity Theft": `Introducing students to various aspects of personal privacy and risks of identity theft in digital world.`,
      "Securing Mobile interactions": `Mobile device safety and methods of secure transactions and activities through mobile`,
      "Social Media & Security": `Social media privacy and potential issues of oversharing and digital foot print`,
      "Identifying and Mitigating Cyber risks": `Identifying various cyber risks like malware infection and introduction on how to protect your device and digital interactions secure`,
      "Keeping your devices safe": `How to protect your home and personal devices safe from hacking`,
    },
    image: "/images/courses/isl.png",
    video: "vnUBqfiLZIk",
    ...courseDefault,
  },
  /* Mental & Emotional Wellbeing */
  // 8-10
  {
    id: 110,
    instructor_id: 1,
    title: "Mental & Emotional Wellbeing",
    slug: "mental-emotional-wellbeing-8-10",
    age: "8-10",
    home:false,
    credits: false,
    self_paced: false,
    desc: "Develop confidence, self respect and self worth while bringing out a positive outlook on life.",
    duration: "5 Classes, Once per Week",
    cost: "15",
    objective:"Introducing children to  the importance of a string mind and how that will impact your future life.",
    stats: ["5", "60", "1:6", "8-10", "15"],
    timeline: {
      "What is mental health": `Introducing children to concepts of mental health - own and others`,
      "Social Awareness": `Importants of appropriate behavior and understanding the cultures across the world`,
      "Emotions & Feelings": `Identifying emotions and their expressions and helping to improve the self esteem`,
      "Positivity": `Power of positive emotions and how to be an optimist`,
      "Mindfulness": `What is mindfulness and how to bring ones attention to present with out judgment`,
    },
    image: "/images/courses/mew.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  },
  // 11-12
  {
    id: 111,
    instructor_id: 1,
    title: "Mental & Emotional Wellbeing",
    slug: "mental-emotional-wellbeing-11-12",
    age: "11-12",
    home:true,
    credits: false,
    self_paced: false,
    desc: "Develop confidence, self respect and self worth while bringing out a positive outlook on life.",
    duration: "5 Classes, Once per Week",
    cost: "15",
    objective:"Introducing rising teens about mental health, positity and mindfulness.",
    stats: ["5", "60", "1:6", "11-12", "15"],
    timeline: {
      "Mental Health": `Introcuding children to importance of mental health and how to be identify any issues for self or friends`,
      "Emotional Intelligence": `Understanding emotional intelligence and its importance`,
      "Positivity and Mindfulness": `Reducing your stress through positivity and mindfulness in life`,
      "Social Skills": `Understanding peer group importance and adolescense ego centrism as a pre-teen`,
      "Helping your mind": `How to sharpen your focus and experience your life with less emotional reactivity`,
    },
    image: "/images/courses/mew.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  },
  // 13-14
  {
    id: 112,
    instructor_id: 1,
    title: "Mental & Emotional Wellbeing",
    slug: "mental-emotional-wellbeing-13-14",
    age: "13-14",
    home:false,
    credits: false,
    self_paced: false,
    desc: "Develop confidence, self respect and self worth while bringing out a positive outlook on life.",
    duration: "6 Classes, Once per Week",
    cost: "15",
    objective:"Introducing teens to various aspects of mental health and mindfulness during teenage and importance of emotional intelligence in life.",
    stats: ["6", "60", "1:6", "13-14", "15"],
    timeline: {
      "Mental Health": `Improtance of mental health and its impact on every thing you do.`,
      "Social and Emotional Learning": `Practical and powerful ways to improve your social and emotional intelligence`,
      "Emotional Intelligence": `Understanding emotional intelligence and its importance. Exercise to evaluate self and improve your EQ`,
      "Self Awareness": `Improving your self esteem and improving your self regulation skills`,
      "Spotting mental issues": `What is depression and anxiety disorders`,
      "Helping your mind": `Positivity and mindfulness exercise and developing media plan`,
    },
    image: "/images/courses/mew.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  },
    /* Health, Hygiene and Puberty for Girls */
  // 11-12
  {
    id: 113,
    instructor_id: 1,
    title: "Health, Hygiene and Puberty for Girls",
    slug: "health-hygiene-and-puberty-for-girls-11-12",
    age: "11-12",
    home:false,
    credits: false,
    self_paced: false,
    desc: "Helping your daughters deal with all sorts of things they maybe worried about, wondering about or may not have considered yet.",
    duration: "6 Classes, Once per Week",
    cost: "15",
    objective:"Introduction to pre-teen health and body changes along with importance of right nutrition and exercise during pre-teen",
    stats: ["6", "60", "1:6", "11-12", "15"],
    timeline: {
      "Big changes ahead": `Introdcing preteens about growth spurt, body changes and other aspects of becoming a teen`,
      "Emotional changes": `Describe how your age and growth affects emotions`,
      "Body care": `Taking care of your body - having a healthy skin, hair and teeth while helping your body to get bone density`,
      "Importance of hygine": `How does pre-teen and teen health impact body for rest of the life`,
      "Healthy food and exercise": `Importance of having healthy food during adolescence. Practical way of healthy eating and exercise habits that helps you`,
      "Pre-menustral and menustral health": `Pre-menustral and menustral health`,
    },
    image: "/images/courses/hhpg.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  },
  // 13-14
  {
    id: 114,
    instructor_id: 1,
    title: "Health, Hygiene and Puberty for Girls",
    slug: "health-hygiene-and-puberty-for-girls-13-14",
    age: "13-14",
    home:true,
    credits: false,
    self_paced: false,
    desc: "Helping your daughters deal with all sorts of things they maybe worried about, wondering about or may not have considered yet.",
    duration: "7 Classes, Once per Week",
    cost: "15",
    objective:"Introducing teenages the key aspects of puberty and how to ensure a healthy and balanced life overcoming any kind of anxiety related to the age",
    stats: ["7", "60", "1:6", "13-14", "15"],
    timeline: {
      "Body & mind": `What changes during teenage and how to take care of your mental wellbeing`,
      "Emotional changes": `Describe how your age and growth affects emotions and how to stay positive`,
      "Body care": `Taking care of your body - having a healthy skin, hair and teeth while helping your body to get bone density`,
      "Importance of hygine": `How does  teen health impact body for rest of the life`,
      "Healthy food and exercise": `Importance of having healthy food during adolescence. Practical way of healthy eating and exercise habits that helps you`,
      "Menustration": `Key facts about teen menustration,PMS, cramps and how to stay healthy and hygenic during the cycle`,
      "Healthy food and exercises": `How to be a healthy teenager`,
    },
    image: "/images/courses/hhpg.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  },
  /* Public Speaking */
  // 11-12
  {
    id: 116,
    instructor_id: 1,
    title: "Public Speaking",
    slug: "public-speaking-11-12",
    age: "11-12",
    home:true,
    credits: true,
    self_paced: false,
    desc: "Dynamic and well-prepared speakers are highly valued. We will help you master the skills needed to organize your thoughts and formulate strong arguments.",
    duration: "7 Classes, Once per Week",
    cost: "15",
    objective:"Introducing pre-teens the importance of public speaking and train kids for public speaking",
    stats: ["7", "60", "1:6", "11-12", "15"],
    timeline: {
      "Why public speaking": `Benefits of public speaking and great speeches that change the world`,
      "Practice more study less": `Organizing a speech and parts of speech`,
      "Body language": `Importance of body language and performance`,
      "Speed, Pace and Clarity": `How to speak and pause sentences to have an impact`,
      "Quick picks": `Sample speech`,
      "Planning for word power": `Preparing for speeches  and impromptu speech techniques`,
      "Practice makes perfect": `Sample speech`,
    },
    image: "/images/courses/ps.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  },
  // 13-14
  {
    id: 117,
    instructor_id: 1,
    title: "Public Speaking",
    slug: "public-speaking-13-14",
    age: "13-14",
    home:false,
    credits: true,
    self_paced: false,
    desc: "Dynamic and well-prepared speakers are highly valued. We will help you master the skills needed to organize your thoughts and formulate strong arguments.",
    duration: "6 Classes, Once per Week",
    cost: "15",
    objective:"Introducing teens to the effective way of public speaking and developing their public speaking skills",
    stats: ["6", "60", "1:6", "13-14", "15"],
    timeline: {
      "Preparing your speech": `Providing quickpick topics, developing supporting information & deciding on style of delivery based on situation`,
      "Organizing your speech": `Organizing a speech and parts of speech`,
      "Body language & eye contacts": `Showing self confidence and present yourself in an interactive way with audience`,
      "Word punch": `Emphasis and different patterns of emphasis`,
      "Speed, Pace and Clarity": `Reducing your own anxiety and improve the skills of fluencu, flexibility and orginality in your speech`,
      "Practice makes perfect": `Sample speech`,      
    },
    image: "/images/courses/ps.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  },
  /* Public Speaking */
  // 11-12
  {
    id: 119,
    instructor_id: 1,
    title: "Dealing with Anxiety",
    slug: "dealing-with-anxiety-11-12",
    age: "11-12",
    home:false,
    credits: false,
    self_paced: false,
    desc: "Know how to manage anxiety so  that it does not interfere with functioning that you would expect for a child during the developmental stage.",
    duration: "4 Classes, Once per Week",
    cost: "15",
    objective:"Introducing pre-teens about manifestation of anxiety and how it impacts day to day life",
    stats: ["4", "60", "1:6", "11-12", "15"],
    timeline: {
      "Understanding Anxiety": `How to differentiate between every day worry and anxiety`,
      "Symptoms of Anxiety": `What are the symptoms and how does it affects you`,
      "Causes of Anxiety": `How is your environment and decisions causing anxiety`,
      "How to overcome anxiety": `How to help yourself and ask for help in case you cannot overcome your anxiety`,
    },
    image: "/images/courses/dwa.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  },
  // 13-14
  {
    id: 120,
    instructor_id: 1,
    title: "Dealing with Anxiety",
    slug: "dealing-with-anxiety-13-14",
    age: "13-14",
    home:true,
    credits: false,
    self_paced: false,
    desc: "Know how to manage anxiety so  that it does not interfere with functioning that you would expect for a child during the developmental stage.",
    duration: "5 Classes, Once per Week",
    cost: "15",
    objective:"Allowing teenagers to understand and overcome anxiety in their life with help of techniques like mindfulness",
    stats: ["5", "60", "1:6", "13-14", "15"],
    timeline: {
      "Understanding Anxiety": `How to differentiate between every day worry and anxiety`,
      "Symptoms of Anxiety": `What are the symptoms and how does it affects you`,
      "Causes of Anxiety": `How is you own thoughts & environment causing anxiety`,
      "How to overcome anxiety": `How to help yourself and ask for help in case you cannot overcome your anxiety`,
      "Seeking parental and professional help": `When to ask help from adults and way to ask help`,
    },
    image: "/images/courses/dwa.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  },
  /* Public Speaking */
  // 11-12
  {
    id: 121,
    instructor_id: 1,
    title: "Communication Skills",
    slug: "communication-skills-11-12",
    age: "11-12",
    home:false,
    credits: true,
    self_paced: false,
    desc: "Improve listening,writing and speaking skills needed to achieve academic and personal success.",
    duration: "5 Classes, Once per Week",
    cost: "10",
    objective:"Introducing children to various aspects of effective communication and social skills",
    stats: ["5", "60", "1:6", "11-12", "10"],
    timeline: {
      "Communication - Evolution": `Introducing children to evolution of communication and approprate methods and ways of communication`,
      "Active Listening": `How to improve the listening skills and use techniques like paraphrasing and summarising`,
      "Writing": `Effective writing and how integrating information from others and your original idea`,
      "Body Language": `Body language concepts and its importance`,
      "Social Skills": `Socializing and interpersonal skills in the modern world`,
    },
    image: "/images/courses/cs.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  }, 
  // 13-14
  {
    id: 122,
    instructor_id: 1,
    title: "Communication Skills",
    slug: "communication-skills-13-14",
    age: "13-14",
    home:true,
    credits: true,
    self_paced: false,
    desc: "Improve listening,writing and speaking skills needed to achieve academic and personal success.",
    duration: "7 Classes, Once per Week",
    cost: "15",
    objective:"Enabling teens to have effective communication with techniques of active listening, efficient writing  and dos and donts in electronic communication.",
    stats: ["7", "60", "1:6", "13-14", "15"],
    timeline: {
      "Communication - Evolution": `Introducing teens to various forms of communication and their effectives on different contexts`,
      "Active Listening": `Explains what is active listening and various techniques in active listening`,
      "Writing": `Explain writing method, how to integrate sources and express consistent point of view while producing a coherent multi para essay`,
      "Body Language": `Provides overview on body language and how it changes with culture`,
      "Social Skills": `Importance of social interactions and how to be an effective communicator in a virtual world. Guding teams to effectively contribute to team discussions`,
      "Comminication - Do's and Dont's in digital world": `How to effectively use electronic communication methods and contribute positively in a disucssion happening in digital world`,
      "Offical and Non official communication": `Types and best practices in communication in the official and non official world`,
    },
    image: "/images/courses/cs.png",
    video: "CGmDCm-bD9k",
    ...courseDefault,
  }, 
];

export const instructorList = [
  {
    id: 1,
    name: "George Smith",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas quos minima incidunt asperiores iure illum nihil, quod aspernatur praesentium dignissimos, repellat itaque reiciendis a ut.",
    stars: 5,
    reviews: 112,
    availability: "Once in a week",
    image: "/images/instructors/instructor1.png",
  },
];